version: '3'

services:

  postgres:
    container_name: gobarber-postgres
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker

  migrate:
    container_name: gobarber-migrate
    build: .
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/database.js --migrations-path src/database/migrations/
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  app:
    container_name: gobarber-app
    build: .
    entrypoint: node_modules/.bin/nodemon src/server.js
    ports:
      - "3333:3333"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - migrate
      - postgres
    links:
      - migrate
      - postgres
